package com.yuanlrc.model;
/*
 * 
 * 用户组
 * 
 */
public class Group {
	
	//用户组id
    private Integer id;
    //用户组名称
    private String groupname;
    //用户组创建时间
    private String createtime;
    //用户组创建人
    private Integer createuserid;
    //用户组创建状态
    private String state;
    //用户组是否删除
    private String isdel;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jxust_group.id
     *
     * @return the value of jxust_group.id
     *
     * @mbggenerated Wed May 10 14:33:15 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jxust_group.id
     *
     * @param id the value for jxust_group.id
     *
     * @mbggenerated Wed May 10 14:33:15 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jxust_group.groupname
     *
     * @return the value of jxust_group.groupname
     *
     * @mbggenerated Wed May 10 14:33:15 CST 2017
     */
    public String getGroupname() {
        return groupname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jxust_group.groupname
     *
     * @param groupname the value for jxust_group.groupname
     *
     * @mbggenerated Wed May 10 14:33:15 CST 2017
     */
    public void setGroupname(String groupname) {
        this.groupname = groupname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jxust_group.createtime
     *
     * @return the value of jxust_group.createtime
     *
     * @mbggenerated Wed May 10 14:33:15 CST 2017
     */
    public String getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jxust_group.createtime
     *
     * @param createtime the value for jxust_group.createtime
     *
     * @mbggenerated Wed May 10 14:33:15 CST 2017
     */
    public void setCreatetime(String createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jxust_group.createuserid
     *
     * @return the value of jxust_group.createuserid
     *
     * @mbggenerated Wed May 10 14:33:15 CST 2017
     */
    public Integer getCreateuserid() {
        return createuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jxust_group.createuserid
     *
     * @param createuserid the value for jxust_group.createuserid
     *
     * @mbggenerated Wed May 10 14:33:15 CST 2017
     */
    public void setCreateuserid(Integer createuserid) {
        this.createuserid = createuserid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jxust_group.state
     *
     * @return the value of jxust_group.state
     *
     * @mbggenerated Wed May 10 14:33:15 CST 2017
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jxust_group.state
     *
     * @param state the value for jxust_group.state
     *
     * @mbggenerated Wed May 10 14:33:15 CST 2017
     */
    public void setState(String state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jxust_group.isdel
     *
     * @return the value of jxust_group.isdel
     *
     * @mbggenerated Wed May 10 14:33:15 CST 2017
     */
    public String getIsdel() {
        return isdel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jxust_group.isdel
     *
     * @param isdel the value for jxust_group.isdel
     *
     * @mbggenerated Wed May 10 14:33:15 CST 2017
     */
    public void setIsdel(String isdel) {
        this.isdel = isdel;
    }
}