package com.yuanlrc.model;

/*
 * 主题表
 * 
 */
public class Zhuti {
	
    private Integer id;

    //主题名称
    private String name;
    //板块的id
    private Integer bankuaiId;
    //排序
    private Integer orderby;
    //创建时间
    private String createtime;
    //板块名称
    private String bankuainame;

    
	public String getBankuainame() {
		return bankuainame;
	}

	public void setBankuainame(String bankuainame) {
		this.bankuainame = bankuainame;
	}

	public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jxust_zhuti.id
     *
     * @param id the value for jxust_zhuti.id
     *
     * @mbggenerated Thu May 04 14:32:45 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jxust_zhuti.name
     *
     * @return the value of jxust_zhuti.name
     *
     * @mbggenerated Thu May 04 14:32:45 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jxust_zhuti.name
     *
     * @param name the value for jxust_zhuti.name
     *
     * @mbggenerated Thu May 04 14:32:45 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jxust_zhuti.bankuai_id
     *
     * @return the value of jxust_zhuti.bankuai_id
     *
     * @mbggenerated Thu May 04 14:32:45 CST 2017
     */
    public Integer getBankuaiId() {
        return bankuaiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jxust_zhuti.bankuai_id
     *
     * @param bankuaiId the value for jxust_zhuti.bankuai_id
     *
     * @mbggenerated Thu May 04 14:32:45 CST 2017
     */
    public void setBankuaiId(Integer bankuaiId) {
        this.bankuaiId = bankuaiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jxust_zhuti.orderby
     *
     * @return the value of jxust_zhuti.orderby
     *
     * @mbggenerated Thu May 04 14:32:45 CST 2017
     */
    public Integer getOrderby() {
        return orderby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jxust_zhuti.orderby
     *
     * @param orderby the value for jxust_zhuti.orderby
     *
     * @mbggenerated Thu May 04 14:32:45 CST 2017
     */
    public void setOrderby(Integer orderby) {
        this.orderby = orderby;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jxust_zhuti.createtime
     *
     * @return the value of jxust_zhuti.createtime
     *
     * @mbggenerated Thu May 04 14:32:45 CST 2017
     */
    public String getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jxust_zhuti.createtime
     *
     * @param createtime the value for jxust_zhuti.createtime
     *
     * @mbggenerated Thu May 04 14:32:45 CST 2017
     */
    public void setCreatetime(String createtime) {
        this.createtime = createtime;
    }
}